<<<<<<< HEAD
name: Cron at 😴
=======
name: Clear DB TrashBin
>>>>>>> 82b1d6c1d563a805640cd61dff83464fd0c9fd32
on:
  schedule:
    - cron: '5 0 * * *'

  workflow_dispatch:

env:
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  cleanTrashBin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: node functions/emptyRecycleBin.js
